# properties-encoder:
#   batch-size: 32
#   train-size: 0.8
#   test-size: 0.2
#   d_model: 16
#   n_heads: 4
#   dr_ff: 4
#   N: 2
#   schedule: [16,32,64]
#   dropout: 0.1
#   epochs: 1
#   l_r: 0.00001
#   lambda_reg: 0.2

# image-decoder:
#   batch-size: 16
#   train-size: 0.8
#   test-size: 0.2
#   d_model: 196608
#   n_heads: 4
#   dr_ff: 4
#   N: 2
#   schedule: [196608,1024,64]
#   dropout: 0.1
#   epochs: 1
#   l_r: 0.00001
#   lambda_reg: 0.2

properties-mlp-autoencoder:
  batch-size: 32
  train-size: 0.8
  test-size: 0.2
  N: 3
  schedule: [16,32,64,128]
  epochs: 20
  l_r: 0.00001
  lambda_reg: 0.2

image-cnn-autoencoder:
  batch-size: 1024
  train-size: 0.8
  test-size: 0.2
  epochs: 10
  l_r: 0.0001
  lambda_reg: 0

