# properties-encoder:
#   batch-size: 32
#   train-size: 0.8
#   test-size: 0.2
#   d_model: 16
#   n_heads: 4
#   dr_ff: 4
#   N: 2
#   schedule: [16,32,64]
#   dropout: 0.1
#   epochs: 1
#   l_r: 0.00001
#   lambda_reg: 0.2

# image-decoder:
#   batch-size: 16
#   train-size: 0.8
#   test-size: 0.2
#   d_model: 196608
#   n_heads: 4
#   dr_ff: 4
#   N: 2
#   schedule: [196608,1024,64]
#   dropout: 0.1
#   epochs: 1
#   l_r: 0.00001
#   lambda_reg: 0.2

# properties-mlp-autoencoder:
#   batch-size: 32
#   train-size: 0.8
#   test-size: 0.2
#   N: 3
#   schedule: [16,32,64,128]
#   epochs: 20
#   l_r: 0.00001
#   lambda_reg: 0.2

image-cnn-autoencoder:
  batch-size: 128
  train-size: 0.8
  test-size: 0.1
  val-size: 0.1
  epochs: 250
  # l_r: 0.00007230110705277947
  l_r: 0.00003
  lambda_reg: 0
  lambda_lpips: 0

